import json, os, stat, importlib
import config_store as cs

def _reset(tmp_path, monkeypatch):
    monkeypatch.setattr(cs, "_DIR", tmp_path / ".itsyou")
    monkeypatch.setattr(cs, "_CONFIG", tmp_path / ".itsyou" / "config.json")
    monkeypatch.setattr(cs, "_USAGE", tmp_path / ".itsyou" / "usage.json")

def test_save_and_get_key_roundtrip(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    cs.set_key("gemini", "AIzaTESTKEY")
    assert cs.get_key("gemini") == "AIzaTESTKEY"
    assert cs.get_provider() == "gemini"

def test_config_file_permission_is_600(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    cs.set_key("openai", "sk-test")
    mode = stat.S_IMODE(os.stat(cs._CONFIG).st_mode)
    assert mode == 0o600

def test_status_never_returns_key(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    cs.set_key("gemini", "secret")
    s = cs.status()
    assert s == {"configured": True, "provider": "gemini"}
    assert "secret" not in json.dumps(s)

def test_env_overrides_file(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    cs.set_key("gemini", "file-key")
    monkeypatch.setenv("GEMINI_API_KEY", "env-key")
    assert cs.get_key("gemini") == "env-key"

def test_admin_key_autogenerated_and_stable(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    k1 = cs.get_or_create_admin_key()
    k2 = cs.get_or_create_admin_key()
    assert k1 == k2 and len(k1) >= 32

def test_daily_usage_increment(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    assert cs.incr_usage("2026-06-15") == 1
    assert cs.incr_usage("2026-06-15") == 2
    assert cs.usage_count("2026-06-15") == 2


def test_reserve_usage_respects_cap_and_rollback(tmp_path, monkeypatch):
    _reset(tmp_path, monkeypatch)
    # cap=2: 두 번 예약 성공, 세 번째는 거부(과금 가드)
    assert cs.reserve_usage("2026-06-15", 2) is True
    assert cs.reserve_usage("2026-06-15", 2) is True
    assert cs.reserve_usage("2026-06-15", 2) is False
    # 롤백 후 다시 한 칸 예약 가능
    cs.release_usage("2026-06-15")
    assert cs.reserve_usage("2026-06-15", 2) is True
